### PR TITLE
Adjust regular expression to avoid look behind expression for Safari compatibility

### LINKED ISSUE #9: Player breaks in Safari due to lookbehind assertion used in regex
Was tracking down a bug in Safari today where the player would not work. I noted the following error in the Javascript console:

```
Unhandled Promise Rejection: SyntaxError: Invalid regular expression: invalid group specifier name
```

I traced it back to this package, where there are a couple of lookbehind assertions being used to neatly match event handler props:

* https://github.com/jwplayer/jwplayer-react/blob/main/src/jwplayer.jsx#L48
* https://github.com/jwplayer/jwplayer-react/blob/main/src/jwplayer.jsx#L56

Lookbehind assertions were added in ES2018. From the [spec](https://262.ecma-international.org/9.0/#sec-intro):

> This specification also includes four new regular expression features: the dotAll flag, named capture groups, Unicode property escapes, and look-behind assertions.

However, lookbehind assertions are not supported in Safari:

* https://caniuse.com/js-regexp-lookbehind
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#browser_compatibility

Also, there don't seem to be any polyfills on accounr of it being [hard to support.
](https://github.com/DmitrySoshnikov/babel-plugin-transform-modern-regexp/issues/5)

### PR DESCRIPTION
**Pull request by m4olivei**
Resolves #9

### CODE REVIEW

**Review by mamaddox — APPROVED** [review]
Nice catch!

**Comment by m4olivei** [comment]
Thanks @mamaddox ! Whats the release process like for this project? When will we see a tagged release with this fix in it?

**Comment by StefanSelfTaught** [comment]
> Thanks @mamaddox ! Whats the release process like for this project? When will we see a tagged release with this fix in it?

Hey, also interested when it will get published. @zetagame @mamaddox

**Comment by mamaddox** [comment]
@StefanSelfTaught and @m4olivei Sorry for the delay! We're still sorting out the release process. We should be getting a new version out today or sometime this week.

**Comment by mamaddox** [comment]
@StefanSelfTaught and @m4olivei The release just went out today 🎉

**Pull request merged**
